version: '3.7'

services:
  api:
    volumes:
      - static:/static
    env_file:
      - .env
    build: ./api
    container_name: sensorsapi_api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    container_name: sensorsapi_db
    volumes:
      - postgres_data:/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: sensorsapi_jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
  sonarqube:
    image: sonarqube
    container_name: sensorsapi_sonarqube
    volumes:
      - sonarqube_data:/var/sonarqube_data
    ports:
      - "9000:9000"

volumes:
  static:
  postgres_data:
  jenkins_home:
  sonarqube_data: