version: '3.7'

services:
  api:
    volumes:
      - static:/static
    env_file:
      - .env
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  static:
  postgres_data: