version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    volumes:
      - sonarqube_data:/var/sonarqube_data
    ports:
      - "9000:9000"

volumes:
  jenkins_home:
  sonarqube_data: